[package]
name = "learn-opengl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
cgmath = "0.18.0"
gl = "0.10.0"
glfw = "0.23.0"
image = "0.24.5"
